//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataSource
    {
        public DataSource()
        {
            this.FoodNutrientDataSourceCrosses = new HashSet<FoodNutrientDataSourceCross>();
        }
    
        public int DataSourceID { get; set; }
        public string Title { get; set; }
        public string Authors { get; set; }
        public string Journal { get; set; }
        public Nullable<int> Year { get; set; }
    
        public virtual ICollection<FoodNutrientDataSourceCross> FoodNutrientDataSourceCrosses { get; set; }
    }
}
