//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Food
    {
        public Food()
        {
            this.FoodFootnoteCrosses = new HashSet<FoodFootnoteCross>();
            this.FoodNutrientCrosses = new HashSet<FoodNutrientCross>();
            this.FoodWeights = new HashSet<FoodWeight>();
        }
    
        public int FoodID { get; set; }
        public int FoodGroupID { get; set; }
        public string Name { get; set; }
        public string ShortName { get; set; }
        public string Manufacturer { get; set; }
        public Nullable<bool> HasCompleteProfile { get; set; }
        public Nullable<decimal> RefusePercent { get; set; }
        public string RefuseDescription { get; set; }
    
        public virtual FoodGroup FoodGroup { get; set; }
        public virtual ICollection<FoodFootnoteCross> FoodFootnoteCrosses { get; set; }
        public virtual ICollection<FoodNutrientCross> FoodNutrientCrosses { get; set; }
        public virtual ICollection<FoodWeight> FoodWeights { get; set; }
    }
}
