//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodWeight
    {
        public int FoodWeightID { get; set; }
        public Nullable<int> FoodID { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<decimal> Value { get; set; }
        public string UnitOfMeasure { get; set; }
        public Nullable<decimal> WeightInGrams { get; set; }
    
        public virtual Food Food { get; set; }
    }
}
