//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodFootnoteCross
    {
        public int FoodFootnoteCrossID { get; set; }
        public Nullable<int> FoodID { get; set; }
        public Nullable<int> FootnoteID { get; set; }
        public string Type { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Footnote Footnote { get; set; }
    }
}
