//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FoodNutrientCross
    {
        public FoodNutrientCross()
        {
            this.FoodNutrientDataSourceCrosses = new HashSet<FoodNutrientDataSourceCross>();
            this.FoodNutrientFootnoteCrosses = new HashSet<FoodNutrientFootnoteCross>();
        }
    
        public int FoodNutrientCrossID { get; set; }
        public Nullable<int> FoodID { get; set; }
        public Nullable<int> NutrientID { get; set; }
        public Nullable<decimal> ValuePerHundredGrams { get; set; }
        public Nullable<bool> IsFortified { get; set; }
    
        public virtual Food Food { get; set; }
        public virtual Nutrient Nutrient { get; set; }
        public virtual ICollection<FoodNutrientDataSourceCross> FoodNutrientDataSourceCrosses { get; set; }
        public virtual ICollection<FoodNutrientFootnoteCross> FoodNutrientFootnoteCrosses { get; set; }
    }
}
