//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Footnote
    {
        public Footnote()
        {
            this.FoodFootnoteCrosses = new HashSet<FoodFootnoteCross>();
            this.FoodNutrientFootnoteCrosses = new HashSet<FoodNutrientFootnoteCross>();
        }
    
        public int FootnoteID { get; set; }
        public string Value { get; set; }
    
        public virtual ICollection<FoodFootnoteCross> FoodFootnoteCrosses { get; set; }
        public virtual ICollection<FoodNutrientFootnoteCross> FoodNutrientFootnoteCrosses { get; set; }
    }
}
