//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NutritionDBEntities : DbContext
    {
        public NutritionDBEntities()
            : base("name=NutritionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DataSource> DataSources { get; set; }
        public DbSet<Food> Foods { get; set; }
        public DbSet<FoodFootnoteCross> FoodFootnoteCrosses { get; set; }
        public DbSet<FoodGroup> FoodGroups { get; set; }
        public DbSet<FoodNutrientCross> FoodNutrientCrosses { get; set; }
        public DbSet<FoodNutrientDataSourceCross> FoodNutrientDataSourceCrosses { get; set; }
        public DbSet<FoodNutrientFootnoteCross> FoodNutrientFootnoteCrosses { get; set; }
        public DbSet<FoodWeight> FoodWeights { get; set; }
        public DbSet<Footnote> Footnotes { get; set; }
        public DbSet<Nutrient> Nutrients { get; set; }
    }
}
